version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
