version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "./wait-for.sh db:5432 -- npm run start"
